# Generated by Django 4.2 on 2023-04-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
