# Generated by Django 4.2 on 2023-04-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feature_age_feature_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='age',
        ),
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='', max_length=500),
        ),
    ]
