# Generated by Django 4.2 on 2023-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='time',
            field=models.CharField(default='12:00', max_length=10),
        ),
        migrations.AddField(
            model_name='available',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
