# Generated by Django 4.2 on 2023-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_available_time_available_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Resv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=31)),
                ('month', models.CharField(default='December', max_length=10)),
                ('year', models.IntegerField(default=2023)),
                ('time', models.CharField(default='12:00', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Available_Tel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=31)),
                ('month', models.CharField(default='December', max_length=10)),
                ('year', models.IntegerField(default=2023)),
                ('time', models.CharField(default='12:00', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Available',
            new_name='Available_Oper',
        ),
    ]
