# Generated by Django 4.2 on 2023-04-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_available_resv_available_tel_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=31)),
                ('month', models.CharField(default='Dec', max_length=3)),
                ('year', models.IntegerField(default=2023)),
                ('time', models.CharField(default='12:00', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Available_Oper',
        ),
        migrations.DeleteModel(
            name='Available_Resv',
        ),
        migrations.DeleteModel(
            name='Available_Tel',
        ),
    ]
