# Generated by Django 4.2 on 2023-05-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_available_date_delete_available_oper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('telephone', models.CharField(default='', max_length=100)),
                ('book_time', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.available_date')),
                ('book_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
            ],
        ),
    ]
