# Generated by Django 4.2 on 2023-05-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='available_date',
            name='time',
        ),
    ]
